import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const siteRoot = path.resolve(scriptDir, "..");
const outputPath = path.join(siteRoot, "data", "problems.json");

// Version-controlled English editorial layer. The public dataset is not
// regenerated directly from the Chinese-language working audit.
const englishCopy = {
  "IM-001": {
    inventoryObject: "Periodic-review lost-sales inventory with positive lead times; the state includes on-hand and pipeline inventory.",
    decision: "Replenishment timing and order quantity, with source selection when supply options are endogenous.",
    uncertainty: "Stochastic demand; extensions may include random supply and stochastic delivery times.",
    question: "Under general demand, positive lead times, and finite parameters, characterize a computationally tractable optimal policy or establish a uniform nonasymptotic guarantee relative to the globally optimal policy. Delineate when base-stock, constant-order, projected-inventory, or richer state-dependent policies are required.",
    sourceEvidence: "The anchor paper treats the system as computationally difficult even when the demand and supply distributions are known, and therefore develops efficient learning methods against structured policy benchmarks.",
    knownProgress: "Regret guarantees are available for selected lead-time regimes and structured benchmarks. Constant-order, base-stock, and projected-inventory policies are supported under special assumptions or asymptotic regimes.",
    currentAssessment: "This is an important but broad structural gap, not a single conjecture stated by one source. A formal release requires a fixed model, benchmark, and performance criterion.",
    nextVerificationAction: "Fix the demand and supply assumptions and the finite-horizon or average-cost criterion; audit 2024-2026 work and forward citations on positive-lead-time lost-sales systems.",
  },
  "IM-002": {
    inventoryObject: "A positive-lead-time lost-sales system with unknown demand and random supply.",
    decision: "Sequential online orders, potentially while learning both demand and supply mechanisms.",
    uncertainty: "Demand distribution, supply realizations or yields, and censored sales feedback.",
    question: "For arbitrary lead times, obtain sublinear regret relative to the globally optimal dynamic policy, or prove an information-theoretic lower bound that explains the lead-time or identifiability restrictions in current results.",
    sourceEvidence: "The benchmark and lead-time restrictions in the anchor paper leave a natural question about when the globally optimal policy is learnable; the paper does not necessarily state this extension as a formal open problem.",
    knownProgress: "Existing algorithms attain regret guarantees against an optimal policy in selected lead-time regimes; more general settings often revert to structured benchmarks such as constant-order policies.",
    currentAssessment: "This formulation is an editorial synthesis. The record must be checked against impossibility results and subsequent work that may have removed the lead-time restriction.",
    nextVerificationAction: "Audit forward citations and lower bounds; separate censored demand, random yield, and unknown-transition information structures.",
  },
  "IM-003": {
    inventoryObject: "Inventory with stochastic lead times, possible order crossing, and indivisible units.",
    decision: "Order quantities and pipeline-inventory control.",
    uncertainty: "Demand and stochastic lead times, including uncertainty in the arrival order.",
    question: "Construct implementable policies with finite-system error bounds for indivisible products and order crossing, without relying on a many-unit scaling limit.",
    sourceEvidence: "The anchor paper develops semi-open-loop policies and proves asymptotic optimality, which leaves finite-system, discrete-unit, and general order-crossing guarantees as natural extensions.",
    knownProgress: "Fluid, diffusion, and other large-scale asymptotic results are available; uniform finite-system guarantees remain comparatively limited.",
    currentAssessment: "This is an editorially synthesized candidate. The exact model, scaling regime, and post-2026 extensions still require verification.",
    nextVerificationAction: "Verify the version of record and search stochastic lead times, order crossing, and finite-system bounds in combination.",
  },
  "IM-004": {
    inventoryObject: "Age-structured perishable inventory with lost sales and positive replenishment lead times.",
    decision: "Ordering, age-based issuance, and disposal or scrapping.",
    uncertainty: "Demand, lifetime, and lead time, with possible random supply.",
    question: "Under general issuing rules and finite parameters, derive policy structure, tractable approximations, or nonasymptotic optimality gaps that do not rely solely on high-shortage-cost or large-system asymptotics.",
    sourceEvidence: "The anchor paper emphasizes the high-dimensional and computationally difficult replenishment problem created by positive lead times and compares inventory-position and projected-inventory-level policies.",
    knownProgress: "Simple policies are asymptotically optimal in selected cost and scale regimes, and worst-case approximations exist for some capacitated perishable systems.",
    currentAssessment: "The source supports a broad research challenge rather than a unique mathematical statement. The record should ultimately separate policy structure, finite-system bounds, and issuing rules.",
    nextVerificationAction: "Extract the conclusion and future-work passages; audit general issuing rules, positive lead times, and finite-gap results.",
  },
  "IM-005": {
    inventoryObject: "Age-structured perishable inventory with capacity constraints and fixed ordering costs.",
    decision: "Batch size, replenishment timing, issuance, and disposal.",
    uncertainty: "Demand and aging, potentially with positive lead times.",
    question: "When capacity, setup costs, positive lead times, and perishability coexist, design scalable policies with tight uniform approximation ratios or additive optimality gaps.",
    sourceEvidence: "The anchor paper establishes approximation algorithms and worst-case guarantees for capacitated perishable inventory; tighter guarantees under richer cost and lead-time structures are natural extensions.",
    knownProgress: "Approximation guarantees are known for selected capacitated perishable models, including balancing and truncated-balancing policies.",
    currentAssessment: "This is an editorial synthesis. A more general model should not be labeled a recognized open problem without direct source support and a current-status audit.",
    nextVerificationAction: "Audit the intersection of fixed ordering costs, positive lead times, and perishability, with particular attention to constant-factor guarantees.",
  },
  "IM-006": {
    inventoryObject: "A dual-sourcing system with regular and expedited suppliers that differ in cost and lead time.",
    decision: "Order quantities by source, inventory targets, and expediting triggers.",
    uncertainty: "Stochastic demand, with possible supply risk and lead-time uncertainty.",
    question: "Under general demand, cost, and lead-time primitives, characterize the exact optimal policy or obtain a uniform finite-system guarantee for a simple policy relative to the globally optimal policy.",
    sourceEvidence: "The anchor paper motivates a recurrent-neural-network policy by the computational difficulty of solving a general dual-sourcing inventory model exactly.",
    knownProgress: "Dual-index, tailored base-surge, critical-set base-surge, distributionally robust, and neural policies are supported under special structures or asymptotic regimes.",
    currentAssessment: "This is a longstanding research challenge. It should be partitioned by single-item versus assembly structure, deterministic versus stochastic lead times, and known versus unknown distributions.",
    nextVerificationAction: "Build a result matrix recording model assumptions, policy class, exact versus asymptotic guarantee, and whether the guarantee is finite-system.",
  },
  "IM-007": {
    inventoryObject: "A multi-component assembly system in which each component can be obtained from regular and expedited sources.",
    decision: "Component-level dual-sourcing orders, critical-set selection, and assembly coordination.",
    uncertainty: "Demand, component costs, and heterogeneous lead times, with possible correlated supply.",
    question: "Outside the current cost or scale regimes, establish nonasymptotic guarantees for dual-sourcing policies in assembly systems and accommodate correlated demand, random supply, and heterogeneous lead times.",
    sourceEvidence: "The anchor paper develops a critical-set base-surge policy with strong performance in specified regimes, exposing the absence of general finite-system guarantees.",
    knownProgress: "Critical-set structure and asymptotic performance guarantees are available in selected regimes.",
    currentAssessment: "The source supports a clear research challenge. A public statement must list the existing theorem conditions so that covered regimes are not relabeled as open.",
    nextVerificationAction: "Extract every theorem assumption and asymptotic regime, then audit subsequent work on dual sourcing in assembly systems.",
  },
  "IM-008": {
    inventoryObject: "A one-warehouse, multi-retailer inventory system, potentially with perishable items or feature-informed demand.",
    decision: "Warehouse replenishment, retailer allocation, and retailer inventory control.",
    uncertainty: "Retailer demand, covariates, and common shocks, potentially with censoring.",
    question: "Without the balance assumption, characterize the exact optimal policy or derive a tractable approximation with tight dependence on network dimension.",
    sourceEvidence: "The anchor paper states that the optimal policy remains unknown after removing the balance assumption and advances the problem through Taylor approximation and a data-driven extension.",
    knownProgress: "Taylor-approximation policies have asymptotic guarantees under many-retailer scaling; data-driven variants establish consistency or sample-performance results.",
    currentAssessment: "This is suitable for the formal-candidate track, but the dated open-status assessment remains provisional pending page-level source storage and independent expert review.",
    nextVerificationAction: "Store the exact source passage and page; audit author follow-up work, forward citations, and exact results that avoid the balance assumption.",
  },
  "IM-009": {
    inventoryObject: "A multiwarehouse, multistore lost-sales system with fixed ordering or shipment costs.",
    decision: "Warehouse and store replenishment, batching, and allocation.",
    uncertainty: "Stochastic demand across locations.",
    question: "Characterize exact finite-horizon or average-cost control, or obtain a uniform performance bound that does not require a long planning horizon.",
    sourceEvidence: "The anchor paper describes exact optimization as structurally complex and computationally prohibitive and proposes a near-optimal mixed (s,S) policy.",
    knownProgress: "Mixed (s,S) policies are near optimal under long-horizon or related asymptotic regimes.",
    currentAssessment: "This is a well-defined research challenge. Finite-horizon, infinite-horizon average-cost, and network-scaling statements must be kept separate.",
    nextVerificationAction: "Verify the horizon and parameter dependence in the existing bounds; audit exact structure and lower bounds for multiechelon lost-sales models with fixed costs.",
  },
  "IM-010": {
    inventoryObject: "A two-echelon stochastic distribution system with fixed shipment costs.",
    decision: "Replenishment quantities, shipment timing, and allocation.",
    uncertainty: "Stochastic demand.",
    question: "Characterize the exact optimal policy or identify a computationally equivalent low-dimensional structure under general conditions.",
    sourceEvidence: "The anchor paper explicitly states that the optimal policy is unknown and develops a modified echelon (r,Q) heuristic.",
    knownProgress: "Modified echelon (r,Q) policies, cost bounds, and asymptotic optimality results are available under selected scalings.",
    currentAssessment: "This is a strong formal candidate, subject to a complete 2021-2026 status audit.",
    nextVerificationAction: "Audit all forward citations and searches for fixed shipment cost, two-echelon distribution, and exact optimal policy; seek author confirmation.",
  },
  "IM-011": {
    inventoryObject: "A one-warehouse, multistore inventory network with price-responsive demand.",
    decision: "Warehouse replenishment, store allocation, and dynamic pricing or markdowns.",
    uncertainty: "Price-dependent demand, store heterogeneity, and replenishment lead times.",
    question: "Under general demand and lead times, characterize exact joint inventory-pricing control or identify a tractable equivalent state representation.",
    sourceEvidence: "The anchor paper explicitly describes optimal joint control as unknown and computationally challenging and develops a structured approximation.",
    knownProgress: "The source provides structural insights and implementable policies; joint inventory-pricing control is better understood in single-location and other special networks.",
    currentAssessment: "This record may enter the formal track only with a mathematical statement that exactly preserves the anchor model.",
    nextVerificationAction: "Store the exact statement and model assumptions; audit author follow-up work and exact results for the same network structure.",
  },
  "IM-012": {
    inventoryObject: "A retail system in which physical and recorded inventory diverge because of transaction errors or unobservable losses.",
    decision: "Replenishment, counting, auditing, correction, and possibly sales control.",
    uncertainty: "Demand, shrinkage, transaction-record errors, and a partially observed state.",
    question: "Find a finite-dimensional sufficient statistic or a provably accurate approximation to full-history partially observed control.",
    sourceEvidence: "The anchor paper shows that the error mechanism changes the information structure and optimal policy, while history-dependent belief states create substantial computational burden.",
    knownProgress: "Threshold structure, belief updates, and heuristic approximations are available for selected error mechanisms.",
    currentAssessment: "This is a clear research challenge, although the source must be checked for an explicit finite-dimensional-representation statement.",
    nextVerificationAction: "Extract the POMDP state and structural results; audit finite-dimensional filters, cycle counting, RFID, and joint audit-control models.",
  },
  "IM-013": {
    inventoryObject: "Large-scale, multi-SKU systems in which corrective actions alter subsequent observations and inventory trajectories.",
    decision: "Anomaly detection, count prioritization, record correction, and replenishment.",
    uncertainty: "Demand, inventory-record errors, and observation-selection bias.",
    question: "Jointly optimize detection, counting, correction, and replenishment when actions affect the data-generating process, and establish guarantees that remain meaningful at retail scale.",
    sourceEvidence: "The anchor paper demonstrates scalable identification and correction of inventory inaccuracies, motivating the endogenous coupling of control and learning.",
    knownProgress: "Scalable detection and repair methods are available; fully integrated dynamic control and counterfactual evaluation are less developed.",
    currentAssessment: "This is an editorial synthesis and belongs in candidate incubation rather than the formal-open-problem track.",
    nextVerificationAction: "Determine whether the anchor model includes replenishment feedback; audit inventory auditing, active learning, endogenous feedback, and off-policy evaluation.",
  },
  "IM-014": {
    inventoryObject: "Positive-lead-time lost-sales inventory in which sales, rather than latent demand, are observed.",
    decision: "Online ordering and exploration.",
    uncertainty: "Unknown demand, censored feedback, and lead times.",
    question: "For general lead times, obtain regret relative to the globally optimal dynamic policy, or establish impossibility and the optimal learning rate.",
    sourceEvidence: "The anchor paper combines Kaplan-Meier estimation with UCB methods under censored demand and lead times, while a possible gap remains between the learnable benchmark and globally optimal control.",
    knownProgress: "Regret and consistency results are available relative to structured policy classes or for selected lost-sales systems.",
    currentAssessment: "This is an editorial synthesis. Its status depends on the anchor paper's benchmark and on subsequent learning results.",
    nextVerificationAction: "Verify the regret benchmark; audit lower bounds and recent work combining censored demand, lead times, and globally optimal dynamic policies.",
  },
  "IM-015": {
    inventoryObject: "A nonstationary inventory system, with the intended extension to multiechelon networks.",
    decision: "Dynamic ordering, repositioning, and the use of predictions.",
    uncertainty: "Demand drift, forecast error, and an unknown variation budget.",
    question: "Extend dynamic-regret guarantees for nonstationary newsvendor models to inventory networks with lead times, while adapting simultaneously to unknown nonstationarity and prediction quality.",
    sourceEvidence: "The anchor paper develops prediction-aware and prediction-free guarantees for the nonstationary newsvendor, providing a benchmark for more complex dynamic inventory networks.",
    knownProgress: "Single-period and single-echelon models admit prediction-augmented algorithms, variation-dependent regret, and robust combination methods.",
    currentAssessment: "The source supports a clear research direction; the network extension is a broader agenda rather than a conjecture stated in the paper.",
    nextVerificationAction: "Separate piecewise-stationary, variation-budget, and adversarial-drift models; audit dynamic regret with lead times and multiechelon coupling.",
  },
  "IM-016": {
    inventoryObject: "A multistage, multi-SKU, or multinode inventory network.",
    decision: "Joint training of demand models and downstream inventory or allocation decisions.",
    uncertainty: "High-dimensional covariates, demand and supply shifts, and cross-domain distribution shift.",
    question: "Develop scalable multistage decision-focused learning methods that enforce operational constraints, admit interpretable performance diagnostics, and generalize across SKUs, regions, and tasks.",
    sourceEvidence: "The source identifies multistage decisions, supply-chain scale, and cross-task generalization as central challenges for decision-focused learning and uses inventory allocation as a motivating setting.",
    knownProgress: "Predict-then-optimize, decision-focused learning, differentiable optimization, and point-prediction decision methods provide a substantial foundation.",
    currentAssessment: "This is a broad agenda supported by an authoritative source. It must not be presented as a single formal open problem.",
    nextVerificationAction: "Decompose the agenda into statistical guarantees, network-scale algorithms, hard constraints, cross-task generalization, and interpretability.",
  },
  "IM-017": {
    inventoryObject: "Inventory systems with high-dimensional states, complex constraints, or nonstationary operating environments.",
    decision: "Reinforcement-learning policies for replenishment, allocation, expediting, and exception management.",
    uncertainty: "Demand and supply shifts, model misspecification, and simulation-to-reality error.",
    question: "Design sample-efficient inventory-control policies that satisfy hard service and feasibility constraints, remain monitorable under distribution shift, and can be interpreted or overridden by human planners.",
    sourceEvidence: "The source highlights reinforcement learning's potential for complex inventory control but also identifies limitations in data, simulation fidelity, reward design, interpretability, trust, convergence diagnostics, and retraining.",
    knownProgress: "Deep reinforcement learning and deep policy iteration have strong computational results and selected theoretical guarantees; simple parametric policies remain important practical benchmarks.",
    currentAssessment: "This is a coherent theory-and-implementation agenda, but it should be decomposed before any component is labeled a mathematical open problem.",
    nextVerificationAction: "Create separate records for feasibility guarantees, sample complexity, policy extraction, distribution shift, and human override.",
  },
  "IM-018": {
    inventoryObject: "Inventory optimization models generated from natural-language requirements or enterprise data.",
    decision: "Model generation, constraint completion, solution, policy recommendation, and tool use.",
    uncertainty: "Demand and supply data, linguistic ambiguity, model stochasticity, and hallucinated structure.",
    question: "Build reproducible benchmarks and verification systems that detect omitted inventory balance, lead-time, service-level, nonanticipativity, and capacity constraints and certify the feasibility and performance of generated policies.",
    sourceEvidence: "The source warns that large language models may omit critical constraints, misclassify mathematical programs, and make optimality verification harder because outputs are stochastic; it advocates guardrails and integration with mathematical models.",
    knownProgress: "Natural-language optimization interfaces, tool-using agents, and constraint-guardrail systems are emerging, but inventory-specific certifiable benchmarks remain immature.",
    currentAssessment: "This agenda is directly supported by a field-level vision article and can form a distinctive theme of the registry.",
    nextVerificationAction: "Define 10-20 recurrent inventory-modeling errors and create human gold standards, feasibility tests, and solver- or proof-based verification protocols.",
  },
  "IM-019": {
    inventoryObject: "AI-assisted replenishment, allocation, and exception-management systems.",
    decision: "Algorithmic recommendations, human overrides, escalation, and allocation of decision rights.",
    uncertainty: "Local private information, model error, selective verification, and environmental change.",
    question: "Identify when planner overrides create value, distinguish private information from algorithm aversion, and design accountable decision rights that learn from overrides without inducing overreliance.",
    sourceEvidence: "The source synthesizes underreliance, overreliance, verification bias, explanation quality, cognitive burden, and accountability, and argues for complementary human-AI design.",
    knownProgress: "Human-AI collaboration has analytical and empirical foundations in healthcare, scheduling, and forecasting; causal evidence in replenishment settings remains limited.",
    currentAssessment: "This is a managerially important OM agenda. Inventory state and inventory performance must remain central so that the record does not collapse into generic human-AI research.",
    nextVerificationAction: "Specify the data and identification strategy for inventory-planner overrides; audit forecast overrides, replenishment overrides, and algorithm aversion.",
  },
  "IM-020": {
    inventoryObject: "A two-layer or multilayer omnichannel network with multiple products sharing inventory and capacity.",
    decision: "Inventory positioning, order fulfillment, rationing, rerouting, and transshipment.",
    uncertainty: "Correlated demand, cancellations or substitution, transportation capacity, and delivery-time uncertainty.",
    question: "Jointly control inventory positioning and real-time fulfillment under correlated demand, shared capacity, and heterogeneous service commitments, with tight guarantees for scalable policies.",
    sourceEvidence: "The anchor paper studies multi-item online fulfillment in a two-layer network and establishes algorithmic guarantees, providing a basis for more tightly coupled positioning and fulfillment models.",
    knownProgress: "Online fulfillment, allocation, transshipment, and dynamic-inventory-network models provide competitive and approximation guarantees in important special cases.",
    currentAssessment: "This is a broad agenda at a mature interface. Cases already covered by online-allocation theory must not be relabeled as open.",
    nextVerificationAction: "Build a model matrix recording endogenous prepositioning, demand correlation, substitution, transportation capacity, cancellations, and service classes.",
  },
  "IM-021": {
    inventoryObject: "Retail or omnichannel systems with noisy inventory states.",
    decision: "Pricing or markdowns, replenishment, auditing, and allocation.",
    uncertainty: "Demand response, inventory-record error, customer heterogeneity, and feedback effects.",
    question: "Jointly optimize pricing and replenishment under inventory-state error, fairness or privacy constraints, and the possibility that high-frequency price updates amplify bullwhip or operational instability.",
    sourceEvidence: "The source links inventory-aware pricing to replenishment and cautions that personalized pricing raises fairness and privacy risks while excessive responsiveness may amplify system volatility.",
    knownProgress: "Joint pricing-inventory control, inventory inaccuracy, fair pricing, and algorithmic stability each have established literatures; their integration is less developed.",
    currentAssessment: "This is an editorial synthesis spanning several mature areas. A systematic review is needed to establish a minimal model with an independent contribution.",
    nextVerificationAction: "Audit joint pricing-inventory control, record inaccuracy, fairness, and stability, then define the smallest identifiable model.",
  },
  "IM-022": {
    inventoryObject: "Service-parts inventory, distributed stocking locations, and additive-manufacturing capacity.",
    decision: "Stock-versus-print choice, stock levels, printer capacity and location, outsourcing, and licensing.",
    uncertainty: "Failure demand, obsolescence, printing time and quality, and lead times.",
    question: "Jointly design service-parts inventory, printing capacity, and predictive diagnostics in a distributed network, accounting for inventory-capacity substitution, location, ownership, and licensing.",
    sourceEvidence: "The anchor paper studies how additive manufacturing changes spare-parts stocking and logistics; predictive printing enabled by AI or IoT adds information and trigger-design questions.",
    knownProgress: "Stock-versus-print structure, centralized versus decentralized printing, and selected predictive-maintenance extensions are available.",
    currentAssessment: "This is an editorial synthesis and currently belongs to a thematic agenda. Capacity location, quality, and licensing should become separate records after verification.",
    nextVerificationAction: "Audit 2020-2026 forward citations and work on predictive additive manufacturing, digital inventory, and intellectual-property licensing.",
  },
  "IM-023": {
    inventoryObject: "Forward inventory, product returns, recoverable items, remanufactured goods, and reusable packaging in a closed-loop system.",
    decision: "Production, remanufacturing, collection, inventory, disposal, deposits, and network design.",
    uncertainty: "Return timing and quality, recovery rates, demand, and residual material value.",
    question: "Under uncertain return quality and repeated use cycles, jointly control new and recovered inventory, collection incentives, network design, and environmental performance through implementable policies.",
    sourceEvidence: "The source establishes an OM research agenda for the circular economy spanning reuse, remanufacturing, recycling, business models, and system design.",
    knownProgress: "Closed-loop supply chains and repairable-item inventory have substantial structural foundations; data-driven, multi-cycle, and platform-mediated recovery systems remain less mature.",
    currentAssessment: "This is a source-backed research agenda. Individual records should be anchored in narrower reviews and primary models.",
    nextVerificationAction: "Separate return quality, reusable packaging, remanufacturing, deposit incentives, and network design, then audit each stream.",
  },
  "IM-024": {
    inventoryObject: "A cross-regional, multisource supply network with safety stock and contingent capacity.",
    decision: "Safety stock, supplier portfolio, flexible capacity, nearshoring, and emergency procurement.",
    uncertainty: "Tail risk, cascading failures, cyberattacks, geopolitical shocks, and institutional change.",
    question: "Design portfolios of inventory buffers, multisourcing, flexible capacity, and network reconfiguration that produce interpretable trade-offs between normal-time efficiency and performance under extreme disruptions.",
    sourceEvidence: "The source treats tail risk, cascading failure, cyber risk, and geopolitical uncertainty as first-order design considerations and emphasizes operational optionality and human override.",
    knownProgress: "Safety stock, multisourcing, backup capacity, and resilient network design each have extensive literatures; integrated multi-mechanism and multiobjective designs remain fragmented.",
    currentAssessment: "This is an authoritative but broad agenda. Each retained subproblem must pass the inventory-at-the-heart test.",
    nextVerificationAction: "Construct a matrix of resilience mechanisms and retain only subproblems for which inventory state or positioning is indispensable.",
  },
  "IM-025": {
    inventoryObject: "Prepositioned disaster supplies, cold-chain products, vaccines, personal protective equipment, and emergency procurement capacity.",
    decision: "Stockpile location and sizing, dynamic replenishment, and equitable allocation.",
    uncertainty: "Disaster demand, supply disruption, infrastructure accessibility, and behavioral response.",
    question: "Integrate ex ante prepositioning with real-time information, flexible procurement, cold-chain requirements, geographic vulnerability, prioritization, and equity in a scalable dynamic model.",
    sourceEvidence: "The source emphasizes strategic location and sizing of critical stockpiles and the use of real-time information for allocation across regions and populations, subject to equity and cold-chain considerations.",
    knownProgress: "Prepositioning, local procurement, vaccine allocation, and equitable humanitarian logistics each have substantial specialized results.",
    currentAssessment: "This is a clear research agenda. Ex ante design, online allocation, and equity or behavioral questions should be separated in future releases.",
    nextVerificationAction: "Audit humanitarian-inventory reviews and recent primary studies, then create distinct design, online-allocation, and field-evidence records.",
  },
  "IM-026": {
    inventoryObject: "Food inventory with multiple batches, heterogeneous expiration dates, and retail display decisions.",
    decision: "Replenishment, batch issuance, display order, markdowns, donation, and disposal.",
    uncertainty: "Demand, expiration, consumer choice, product visibility, and temperature-dependent quality.",
    question: "Jointly control multi-expiration-date inventory, dynamic pricing, display or information disclosure, and donation or disposal to balance cost, service, waste, and life-cycle emissions.",
    sourceEvidence: "The source develops a food-waste research agenda spanning technology, logistics, incentives and coordination, business models, and behavioral operations.",
    knownProgress: "Perishable replenishment, dynamic markdowns, multiple expiration dates, and donation have established models; integrated decisions and field validation remain limited.",
    currentAssessment: "This is an authoritative research agenda. Formal mathematical questions require narrower model statements.",
    nextVerificationAction: "Partition the area into expiration-date multiplicity, consumer search, markdowns, donation, cold chain, and emissions, and audit each stream.",
  },
  "IM-027": {
    inventoryObject: "Inventory, trade credit, and external finance for a working-capital-constrained firm.",
    decision: "Ordering, financing, payment, insurance, contracting, and emergency procurement.",
    uncertainty: "Demand, supply disruption, financing cost, default, and asymmetric information.",
    question: "When financing constraints and supply disruptions interact dynamically, jointly optimize inventory and liquidity and characterize the structural feedback among working capital, resilience, and operating policy.",
    sourceEvidence: "The source reviews the finance-operations-risk interface and identifies inventory-financing interactions as a central direction.",
    knownProgress: "Inventory financing, trade credit, bankruptcy risk, and supply disruption each have mature model classes.",
    currentAssessment: "This is an editorial synthesis. A precise information structure and dynamic benchmark are required before it can become an auditable formal problem.",
    nextVerificationAction: "Audit dynamic models combining working capital, inventory finance, disruption, and trade credit, and locate explicit unresolved statements.",
  },
  "IM-028": {
    inventoryObject: "Inventory systems that use forecasting, reinforcement learning, generative AI, or autonomous agents.",
    decision: "Model selection, deployment, retraining, human supervision, and allocation of computational resources.",
    uncertainty: "Model drift, decision error, computing prices, energy use, and emissions.",
    question: "Develop a decision-level accounting framework that evaluates inventory cost and service improvements jointly with the life-cycle cost of data, computing, maintenance, supervision, governance, and carbon emissions.",
    sourceEvidence: "The source calls for comparing the marginal operating benefit of AI with its resource cost and cautions against resource-intensive methods when simpler approaches perform similarly.",
    knownProgress: "Model-efficiency metrics, green computing, monitoring systems, and conventional inventory-cost measures provide components, but a unified decision-level framework is not established.",
    currentAssessment: "This is a source-backed infrastructure agenda, not a single mathematical conjecture.",
    nextVerificationAction: "Define system boundaries, baseline policies, carbon-accounting conventions, and decision-quality metrics, and identify suitable deployment data.",
  },
  "IM-029": {
    inventoryObject: "Multiple periodically replenished items whose phases are staggered to smooth a shared capacity or workload.",
    decision: "Replenishment phases, group synchronization, and staggering schedules.",
    uncertainty: "Demand or cost parameters, cycle lengths, and shared resource load.",
    question: "Historical question: can one derive improved approximation and structural guarantees for inventory staggering, including groupwise synchronization and sampling-based construction?",
    sourceEvidence: "The anchor paper develops new approximation guarantees and directly establishes sampling-complexity and groupwise-synchronization results that had been treated as candidate gaps in the initial audit.",
    knownProgress: "The 2026 paper proves the principal guarantees attached to the original record. Extensions with additional side constraints may remain interesting but constitute different questions.",
    currentAssessment: "Reclassified as a resolved control. The earlier formal-candidate label conflated results proved in the anchor paper with genuinely unresolved extensions.",
    nextVerificationAction: "Map each historical question to the corresponding theorem and retain only assumption-changing extensions as separate candidate records.",
  },
  "IM-030": {
    inventoryObject: "A positive-lead-time lost-sales system in which latent demand is censored by sales.",
    decision: "Online ordering and learning of a base-stock level.",
    uncertainty: "Unknown demand and censored sales feedback.",
    question: "Historical question: can an algorithm attain near-optimal regret relative to the best base-stock policy in a lost-sales system with lead times?",
    sourceEvidence: "The source explicitly aims to close this gap and proves learning guarantees relative to the optimal base-stock policy.",
    knownProgress: "The anchor paper and subsequent work close the central gap for the base-stock benchmark. Regret relative to the globally optimal dynamic policy is a distinct problem.",
    currentAssessment: "This record is retained as a resolved control so that benchmark-specific resolutions are not later presented as active open problems.",
    nextVerificationAction: "Map the historical statement, resolution theorem, and later extensions, preserving the distinction between a base-stock and globally optimal benchmark.",
  },
  "IM-031": {
    inventoryObject: "A multi-item joint-replenishment system with a shared fixed ordering cost.",
    decision: "Joint and item-specific replenishment timing, quantities, and dynamic policy selection.",
    uncertainty: "Deterministic or stochastic demand, depending on the historical formulation.",
    question: "Historical question: can dynamic joint replenishment admit a computationally efficient near-optimal policy in both continuous and discrete time?",
    sourceEvidence: "The source states that it resolves two foundational open questions by constructing near-optimal dynamic policies or approximation schemes.",
    knownProgress: "Earlier work established approximations and special cases; the anchor paper supplies stronger near-optimal schemes for the stated models.",
    currentAssessment: "This record is retained as a resolved control. The precise assumptions of the closed problems must not be extrapolated to broader variants.",
    nextVerificationAction: "Verify the original problem statements and map the continuous- and discrete-time assumptions to the resolution theorems.",
  },
};

const provisionalWorkflow = {
  extracted: "complete",
  sourceVerified: "provisional",
  literatureAudited: "provisional",
  expertVerified: "not-recorded",
  sourceLabel: "SV-LA (provisional)",
};

const additions = [
  {
    id: "IM-032",
    titleEn: "Resolved control: removing the logarithmic loss for reusable-resource allocation",
    imClass: "IM-Core",
    evidenceType: "Type A",
    primaryDomain: "Reusable Inventory / Online Allocation",
    cohenLayer: "Execution",
    inventoryObject: "Reusable resource units that become unavailable for a stochastic duration and later return to inventory.",
    decision: "Online assortment or allocation, admission control, and inventory-feasibility enforcement.",
    uncertainty: "Nonstationary arrivals, heterogeneous request rewards, usage durations, and customer choice.",
    question: "Historical question: can the competitive guarantee for reusable resources be improved from 1-O(sqrt(log k/k)) to 1-O(1/sqrt(k))?",
    sourceAuthors: "Feng, Niazadeh, and Saberi (2024)",
    sourceTitle: "Technical Note—Near-Optimal Bayesian Online Assortment of Reusable Resources",
    journal: "Operations Research",
    doiUrl: "https://doi.org/10.1287/opre.2020.0687",
    sourceEvidence: "Open Problems in OR record W4285091035_p0 extracts the paper's explicit request to remove the logarithmic factor. Aminian, Niazadeh, and Nuti (2026) subsequently obtain 1-sqrt(2/(pi k))+O(1/k) for a Bayesian reusable-resource allocation model and state that this solves the earlier rate question.",
    knownProgress: "The 2024 paper obtains 1-O(sqrt(log k/k)). The 2026 working paper matches the leading nonreusable benchmark order for a reusable allocation model.",
    currentAssessment: "This is a scope-sensitive resolved control, not an active open problem. The 2026 allocation model must still be mapped carefully to the customer-choice assortment model before claiming resolution of every assortment variant.",
    statusCode: "RS",
    inclusionRecommendation: "Include - Resolved Archive",
    track: "Resolved archive",
    confidence: "Medium",
    expertVerificationRequired: "Yes",
    nextVerificationAction: "Complete an assumption-by-assumption mapping between the reusable allocation and assortment models, including choice substitution, arrival processes, rewards, and duration distributions.",
    lastAuditDate: "2026-09-02",
    notes: "Cross-registry provenance: Open Problems in OR W4285091035_p0. Candidate resolution: Aminian, Niazadeh, and Nuti (2026), https://ssrn.com/abstract=6384158.",
    verificationStage: "SV-LA (provisional)",
    workflow: { ...provisionalWorkflow },
    auditFlags: ["Resolution scope requires expert review before the assortment variant is treated as fully closed."],
  },
  {
    id: "IM-033",
    titleEn: "Sharp decentralization condition during inventory disruptions",
    imClass: "IM-Core",
    evidenceType: "Type A",
    primaryDomain: "Multi-Echelon / Disruptions",
    cohenLayer: "Execution",
    inventoryObject: "A distribution system with a central warehouse, multiple retailers, expediting, and an upstream disruption mode.",
    decision: "Whether disrupted-mode inventory should be centralized at the warehouse or decentralized across retailers.",
    uncertainty: "Poisson demand, disruption duration, upstream availability, and expedited fulfillment cost.",
    question: "Determine the smallest universal constant epsilon_0 for which the tail comparison underlying the decentralization result holds whenever lambda >= a + epsilon_0. The current proof uses epsilon_0=1, whereas a counterexample implies epsilon_0>0.25.",
    sourceAuthors: "Zhao, Birge, DeValve, and Inman (2026)",
    sourceTitle: "Managing Multitier Inventory Networks with Expediting Under Normal and Disrupted Modes",
    journal: "Manufacturing & Service Operations Management",
    doiUrl: "https://doi.org/10.1287/msom.2023.0249",
    sourceEvidence: "Endnote 3 explicitly asks whether the sufficient requirement lambda >= a+1 can be tightened to lambda >= a+epsilon_0 and records a counterexample showing that any universal epsilon_0 must exceed 0.25.",
    knownProgress: "The paper proves the required Poisson-tail comparison for epsilon_0=1 and uses it to obtain a simple decentralization criterion during disruptions.",
    currentAssessment: "This is a precise formal candidate from a 2026 UTD journal article. Its operational importance is narrower than the paper's broader inventory-positioning contribution, and current open status still requires a targeted mathematical literature audit.",
    statusCode: "OF",
    inclusionRecommendation: "Include - Formal Track",
    track: "Formal candidate",
    confidence: "High",
    expertVerificationRequired: "Yes",
    nextVerificationAction: "Store the exact endnote and lemma statement, search sharp Poisson-tail comparison results, and seek confirmation from the authors or a probability expert.",
    lastAuditDate: "2026-09-02",
    notes: "Exact source location: Section 7, Endnote 3 of the publisher PDF.",
    verificationStage: "SV-LA (provisional)",
    workflow: { ...provisionalWorkflow },
    auditFlags: [],
  },
  {
    id: "IM-034",
    titleEn: "Necessary conditions for four-threshold inventory reset policies",
    imClass: "IM-Core",
    evidenceType: "Type A",
    primaryDomain: "Perishables / Controlled Resets",
    cohenLayer: "Execution",
    inventoryObject: "Inventory that must be fully reset periodically and may also be reset early, as in water storage or limited-duration retail product lines.",
    decision: "Whether to discard all inventory and, conditional on retaining or resetting the system, how much to order.",
    uncertainty: "Demand, contamination or aging cost, shortage cost, and reset cost.",
    question: "Characterize weaker or necessary conditions under which the optimal reset-and-order policy retains the four-threshold structure established under the paper's sufficient conditions.",
    sourceAuthors: "Lee, Mintz, Aswani, Shen, and Yang (2025)",
    sourceTitle: "Optimal Policy for Inventory Management with Periodic and Controlled Resets",
    journal: "Manufacturing & Service Operations Management",
    doiUrl: "https://doi.org/10.1287/msom.2022.0318",
    sourceEvidence: "The conclusion states that the sufficient conditions for the threshold structure appear conservative rather than necessary and leaves their relaxation to future research.",
    knownProgress: "Under the stated sufficient conditions, the paper proves a four-threshold optimal policy and provides an efficient numerical method.",
    currentAssessment: "This is an explicit structural question in a 2025 UTD journal article. A formal release should specify which assumptions are candidate relaxations and what counterexamples are already known.",
    statusCode: "OF",
    inclusionRecommendation: "Include - Formal Track",
    track: "Formal candidate",
    confidence: "High",
    expertVerificationRequired: "Yes",
    nextVerificationAction: "Extract each sufficient condition, test necessity computationally, and audit subsequent work on controlled resets and nonconvex inventory value functions.",
    lastAuditDate: "2026-09-02",
    notes: "Exact source location: conclusion of the published paper; the statement is structural rather than a single numerical conjecture.",
    verificationStage: "SV-LA (provisional)",
    workflow: { ...provisionalWorkflow },
    auditFlags: [],
  },
  {
    id: "IM-035",
    titleEn: "Optimal replenishment and issuance under age-sensitive demand and general lifetimes",
    imClass: "IM-Core",
    evidenceType: "Type B",
    primaryDomain: "Perishables / Age-Sensitive Demand",
    cohenLayer: "Execution",
    inventoryObject: "A finite-horizon perishable-inventory system in which customer utility depends on the remaining lifetime of the issued unit.",
    decision: "Joint replenishment and age-based issuance.",
    uncertainty: "Demand and the age composition of available inventory.",
    question: "For general product lifetimes, characterize the optimal joint replenishment and issuance policy or derive a worst-case performance guarantee for a tractable bucket policy.",
    sourceAuthors: "Goyal and Sapra (2025)",
    sourceTitle: "Please Customers or Prevent Wastage? Replenishment and Issuance Policy for a Perishable Product with Age-Sensitive Demand",
    journal: "Manufacturing & Service Operations Management",
    doiUrl: "https://doi.org/10.1287/msom.2023.0578",
    sourceEvidence: "The paper gives a threshold characterization for a two-period lifetime but reports that optimal issuance can be complex for longer lifetimes; its general-lifetime contribution relies on bucket policies and computational performance.",
    knownProgress: "For a two-period lifetime, the optimal issuance rule first uses new units up to a threshold and then follows FIFO. For general lifetimes, the best bucket policy is close to optimal on the reported instances, and the proposed heuristic is asymptotically optimal as unit price grows.",
    currentAssessment: "This is a source-backed research challenge rather than a stated conjecture. The absence of a worst-case bound should be verified against subsequent work before the record is promoted.",
    statusCode: "PR",
    inclusionRecommendation: "Include - Research Agenda Track",
    track: "Research agenda",
    confidence: "Medium",
    expertVerificationRequired: "Yes",
    nextVerificationAction: "Audit forward citations and general-lifetime perishable issuing models; separate exact policy structure from worst-case approximation guarantees.",
    lastAuditDate: "2026-09-02",
    notes: "Publisher abstract and paper scope verified; the open formulation is an editorial synthesis.",
    verificationStage: "SV-LA (provisional)",
    workflow: { ...provisionalWorkflow },
    auditFlags: [],
  },
];

const data = JSON.parse(await fs.readFile(outputPath, "utf8"));
for (const record of data.records) {
  const copy = englishCopy[record.id];
  if (!copy) throw new Error(`Missing English curation for ${record.id}`);
  Object.assign(record, copy);
}

const staggering = data.records.find((record) => record.id === "IM-029");
Object.assign(staggering, {
  titleEn: "Resolved control: approximation guarantees for inventory staggering",
  statusCode: "RS",
  inclusionRecommendation: "Include - Resolved Archive",
  track: "Resolved archive",
  confidence: "High",
  expertVerificationRequired: "No",
  verificationStage: "LA (provisional)",
  workflow: {
    extracted: "complete",
    sourceVerified: "provisional",
    literatureAudited: "provisional",
    expertVerified: "not-recorded",
    sourceLabel: "LA (provisional)",
  },
  auditFlags: [],
});

for (const addition of additions) {
  const index = data.records.findIndex((record) => record.id === addition.id);
  if (index >= 0) data.records[index] = addition;
  else data.records.push(addition);
}

data.records.sort((a, b) => a.id.localeCompare(b.id));
const active = data.records.filter((record) => record.track !== "Resolved archive");
data.schemaVersion = "1.1";
data.dataVersion = "2026-09-02";
data.generatedForPrototype = "2026-09-02";
data.disclaimer = "No active record is expert-verified. Open status is bounded by the documented search scope and audit date.";
data.summary = {
  totalRecords: data.records.length,
  activeCandidates: active.length,
  formalCandidates: data.records.filter((record) => record.track === "Formal candidate").length,
  researchAgendas: data.records.filter((record) => record.track === "Research agenda").length,
  candidateIncubation: data.records.filter((record) => record.track === "Candidate incubation").length,
  resolvedArchive: data.records.filter((record) => record.track === "Resolved archive").length,
  expertVerifiedActive: active.filter((record) => record.workflow?.expertVerified === "complete").length,
};

await fs.writeFile(outputPath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
console.log(`Curated ${data.records.length} records in English at ${outputPath}`);
